### ISSUE TITLE
Config file format?

### ISSUE THREAD

**Issue by klept0** [TychoTheTaco/Prime-Loot-Claimer#1]
Is there a specific config file setup we should use when trying to run this?

**Comment by TychoTheTaco** [comment]
No config file is required, but if you want you can specify these options in a `config.json` file:
```
{
  "headful": true,
  "browser_args": ["--mute-audio"]
}
```

BTW, I'm not sure this code still works since I haven't used it in a while.

**Comment by klept0** [comment]
That bit fixes it so I can launch but it does throw an error so you know 

TimeoutError: Timeout exceeded while waiting for event
    at Timeout.<anonymous> (C:\Prime-Loot-Claimer-master\node_modules\puppeteer\lib\cjs\puppeteer\common\helper.js:122:28)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

Unless you plan on updating this for yourself I will close this out and I appreciate the reply
